"""从自描述 Schema 生成统一中文字段说明，并检查产物是否过期。"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def render(schema_root: Path) -> str:
    """按文件名稳定排序生成 Schema 用途、字段、枚举、规则和反例说明。"""

    lines=["# Schema 字段说明（自动生成）","","<!-- generated by scripts/generate_schema_docs.py; do not edit manually -->","","本文件从 `schemas/*.json` 的自描述元数据生成。`$id` 是逻辑身份，不保证网络可访问；验证器从本地注册表离线解析。",""]
    for path in sorted(schema_root.glob("*.json")):
        if path.name in {"catalog.json","schema-meta.schema.json"}: continue
        payload=json.loads(path.read_text(encoding="utf-8")); ext=payload.get("x-context-atlas")
        if not isinstance(ext,dict): continue
        lines.extend([f"## `{path.name}`","",str(payload.get("description",ext.get("purpose",""))),"",f"- 稳定 ID：`{payload.get('$id','不适用')}`",f"- 使用时机：{'；'.join(ext.get('use_when',[]))}",f"- 不应使用：{'；'.join(ext.get('do_not_use_when',[]))}",f"- 权威位置：`{ext.get('canonical_location','')}`",""])
        props=payload.get("properties",{})
        if isinstance(props,dict) and props:
            lines.extend(["| 字段 | 必填 | 说明 | 示例 |","| --- | --- | --- | --- |"])
            required=set(payload.get("required",[]))
            for field,definition in props.items():
                if not isinstance(definition,dict):continue
                example=definition.get("examples",[""])[0] if definition.get("examples") else ""
                description=str(definition.get("description","")).replace("|","\\|")
                required_label="是" if field in required else "否"
                lines.append(f"| `{field}` | {required_label} | {description} | `{json.dumps(example,ensure_ascii=False)}` |")
            lines.append("")
        enums=payload.get("enums",{})
        if isinstance(enums,dict) and enums:
            lines.extend(["### 枚举取值",""])
            for field in enums:
                definition=props.get(field,{}) if isinstance(props,dict) else {}
                branches=definition.get("oneOf",[]) if isinstance(definition,dict) else []
                lines.append(f"- `{field}`：")
                for branch in branches:
                    when="；".join(branch.get("x-context-atlas",{}).get("use_when",[]))
                    lines.append(f"  - `{branch.get('const')}`：{branch.get('description','')} 使用条件：{when}")
            lines.append("")
        rules=ext.get("rules",[])
        if rules:
            lines.extend(["### 规则",""])
            for item in rules:
                diagnostic=f"，诊断 `{item['diagnostic_code']}`" if item.get("diagnostic_code") else ""
                lines.append(f"- `{item['id']}`（{item['enforcement']}{diagnostic}）：{item['description']} 修复：{item['remediation']}")
            lines.append("")
        bad=ext.get("invalid_examples",[])
        if bad:
            lines.extend(["### 反例",""])
            for item in bad: lines.append(f"- `{item['case']}` → `{item['expected_rule']}`：{item['reason']}")
            lines.append("")
    return "\n".join(lines).rstrip()+"\n"


def main() -> int:
    """解析参数，再生成或比较文档，最后返回对应检查结果。"""

    parser=argparse.ArgumentParser();parser.add_argument("--root",type=Path,default=Path.cwd());parser.add_argument("--check",action="store_true");args=parser.parse_args()
    target=args.root/"schemas"/"字段说明.md";content=render(args.root/"schemas")
    if args.check:
        if not target.is_file() or target.read_text(encoding="utf-8") != content:
            print(f"Schema documentation is stale: {target}");return 1
        print("Schema documentation is current");return 0
    target.write_text(content,encoding="utf-8");print(target);return 0

if __name__ == "__main__": raise SystemExit(main())
